exports.scanOptions = {
    car_information: [
        "car_brand",
        "car_model",
        "manufacture_year",
        "kilometer_number",
        "car_brand",
        "car_plate",
        "vin",
        "gazoline_type",
        "car_color",
        "gearbox",
        "documents",
        "chassis_matching",
        "nbr_seats",
        "drive_type",
        "km_after_inspection"
    ],
    interior: [
        "internal_order",
        "seats",
        "airBags",
        "floorMats",
        "windows",
        "AC",
        "Radio",
        "Screen",
        "control_buttons",
        "warning_signs",
        "window_buttons",
        "door_handles",
        "surface",
    ],
    exterior: [
        "external_structure",
        "exterior_lights",
        "Tires",
        "Wiper_Blades",
        "Dents",
        "insode_trunk",
        "sill",
        "window_glasses",
        "upper_window_glass",
        "front_rear_glass",
        "side_mirror",
        "door_handle"
    ],
    mechanical: [
        "engine_transmission",
        "differential",
        "engine_cooling_system",
        "fluid_leaks",
        "Brake_Arms_Shock_absorbs",
        "AC_system",
        "electricity_system",
        "computer_system_scanned"
    ]
}